version:     "0001--03-Mar-2023"
copyright:   "2023"
author:      "Linus A. W."
title:       "PPL: LIDAR Project Report"
githublink:  "https://github.com/linusabhyasaui/ppl-blog/"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
